id: Service
desc: Executes assigned code when a serviced vehicle gets rearmed, repaired or refueled. The code executes with interval while the serviced vehicle receives service. If the code returns [[true]] the default on-screen service message is not shown.
params:
- name: serviceVehicle
  desc: service vehicle
  type: Object
- name: servicedVehicle
  desc: vehicle receiving service
  type: Object
- name: serviceType
  desc: 0 - MINOR REPAIR, 1 - REPAIR, 2 - REFUEL, 3 - REARM
  type: Number
- name: needsService
  desc: how much serviced vehicle [[needService | needsSevice]], 0..1 where 0 - no need, 1 - need a lot
  type: Number
- name: autoSupply
  desc: '[[true]] if supply started by proximity, [[false]] if supply started due to user action'
  type: Boolean
since:
  arma3: '2.12'
argument_loc: Unspecified
effect_loc: Unspecified
examples:
- "addMissionEventHandler [\"Service\", {\n\tparams [\"_serviceVehicle\", \"_servicedVehicle\", \"_serviceType\", \"_needsService\", \"_autoSupply\"];\n}];"
