name: campaignConfigFile
desc: Returns root of campaign description.ext entries hierarchy.
groups:
- Config
syntax:
- call: Nular
  ret:
    type: Config
argument_loc: Unspecified
effect_loc: Unspecified
since:
  arma1: '1.0'
  arma2: '1.0'
  arma2oa: '1.50'
  tkoh: '1.0'
  arma3: '0.50'
examples:
- <sqf>_config = campaignConfigFile;</sqf>
see_also:
- configFile
- missionConfigFile
