name: campaignConfigFile
desc: Returns root of campaign description.ext entries hierarchy.
groups:
- Config
syntax:
- call: Nular
  ret:
    type: Config
argument_loc: Unspecified
effect_loc: Unspecified
since: {}
examples:
- <sqf>_config = campaignConfigFile;</sqf>
see_also:
- configFile
- missionConfigFile
