name: configNull
desc: "A non-existing [[Config]].\n\n{{Feature|important|\nUnlike other null values ([[objNull]], [[grpNull]], etc), [[configNull]] returns [[true]] when compared to itself.\n<sqf>\nconfigNull == configNull;\t\t\t\t\t\t\t// returns true\nisNull configNull;\t\t\t\t\t\t\t\t\t// returns true\nconfigNull isEqualTo configNull;\t\t\t\t\t// returns true\nconfigNull == configFile >> \"ANonExistentEntry\";\t// returns true\n</sqf>\n}}"
groups:
- Variables
- Config
syntax:
- call: Nular
  ret:
    type: Config
  params: []
argument_loc: Unspecified
effect_loc: Unspecified
since:
  arma3: '1.56'
examples:
- <sqf>_config = missionNamespace getVariable ["myConfig", configNull];</sqf>
- <sqf>str configNull; // returns ""</sqf>
see_also:
- controlNull
- displayNull
- grpNull
- locationNull
- objNull
- taskNull
- teamMemberNull
- scriptNull
- typeName
- isNull
