name: configClasses
desc: "Returns an array of config entries which meet criteria in condition code. Command iterates through all available config sub classes of the given config class. Current looked at config is stored in _x variable (similar to alternative [[count]] command implementation). Condition has to return [[true]] in order for the looked at config to be added to the resulting array. Slightly faster than [[configProperties]], but doesn't account for config properties or inherited entries.\n{{Feature|important| \n* The condition code passed to [[configClasses]] should only be used for '''simple filter expressions''' and nothing more\n* Do not use {{hl|\"[[isClass]] [[Magic Variables#x|_x]]\"}} in the condition. The engine does this check already<br><br>\n* {{arma3}} v2.02 brought specific engine optimisations for the following conditions:\n** {{hl|\"[[true]]\"}} \n** {{hl|\"[[getNumber]] ([[Magic Variables#x|_x]] >> 'scope') > 0\"}}}}"
groups:
- Config
syntax:
- call: !Binary
  - condition
  - config
  ret:
    type: ArrayUnknown
    desc: array of [[Config]]s
  params:
  - name: condition
    type: String
  - name: config
    type: Config
- call: !Unary
  - config
  - depth
  - includeInherited
  - allSubclasses
  - classNames
  ret:
    type: ArrayUnknown
    desc: array of [[Config]]s or [[Strings]], which represent class names.
  params:
  - name: config
    desc: target config
    type: Config
  - name: depth
    desc: how many levels of subclasses to go deep
    type: Number
  - name: includeInherited
    desc: '[[true]] to look through inherited classes'
    type: Boolean
  - name: allSubclasses
    desc: '[[true]] to return all subclasses, [[false]] - to return only the last tier.'
    type: Boolean
  - name: classNames
    desc: '(Optional, default: [[false]]) when [[true]] class names [[String]]s are returned, when [[false]] - [[Config]]s are returned.'
    type: Boolean
    optional: true
  since:
    arma3: '2.22'
argument_loc: Unspecified
effect_loc: Unspecified
since:
  arma3: '1.24'
examples:
- |-
  collect all CfgVehicles configs:
  <sqf>_configs = "true" configClasses (configFile >> "CfgVehicles");</sqf>
- |-
  Return all classes that can transport 10 and more soldiers:
  <sqf>_transporters = "getNumber (_x >> 'transportSoldier') >= 10" configClasses (configFile >> "CfgVehicles");</sqf>
- |-
  Return all classes that inherit from 'RscText':
  <sqf>hint str ("inheritsFrom _x == (configFile >> 'RscText')" configClasses configFile);</sqf>
- |-
  Return children:
  <sqf>configClasses [configFile >> "CfgGroups", 0, true, true, true]
  //Returns ["West","East","Indep","Empty"]</sqf>
see_also:
- Config
- configFile
- missionConfigFile
- configProperties
- configHierarchy
- BIS_fnc_returnChildren
