name: configFile
desc: Return root of config entries hierarchy.
groups:
- Config
syntax:
- call: Nular
  ret:
    type: Config
argument_loc: Unspecified
effect_loc: Unspecified
since: {}
examples:
- <sqf>_isMyClassActive = isClass (configFile >> "CfgPatches" >> "MyClass");</sqf>
see_also:
- missionConfigFile
- campaignConfigFile
