name: configSourceAddonList
desc: Returns an array of addons ([[CfgPatches]]) in which the given config class is defined.
groups:
- Mods and Addons
- Config
syntax:
- call: !Unary config
  ret:
    type: !ArrayUnsized
      value: String
  right: !Item
    name: config
    type: Config
argument_loc: Unspecified
effect_loc: Unspecified
since: {}
examples:
- <sqf>_addons = configSourceAddonList (configFile >> "CfgVehicles" >> "Man"); // returns ["A3_Data_F", "A3_Characters_F", "A3_Data_F_Curator", "A3_Air_F_Heli"]</sqf>
see_also:
- configFile
- configSourceMod
- configSourceModList
