name: configName
desc: Returns name of config entry.
groups:
- Config
syntax:
- ret:
    type: String
  right: !Item
    name: config
    type: Config
argument_loc: Unspecified
effect_loc: Unspecified
since:
  arma1: '1.0'
  arma2: '1.0'
  arma2oa: '1.50'
  tkoh: '1.0'
  arma3: '0.50'
examples:
- <sqf>_name = configName (configFile >> "CfgVehicles"); // result is "CfgVehicles"</sqf>
see_also:
- configFile
- a
- /
- b
- config
- greater
- greater
- name|config
- '>>'
- name
- count
- getArray
- getText
- getNumber
- inheritsFrom
- isArray
- isClass
- isNumber
- isText
- select
