name: configHierarchy
desc: Returns hierarchy of the given config class. Just like with [[inheritsFrom]], only complete config classes are supported (before {{GVI|arma3|2.14|size= 0.75}}). Since {{GVI|arma3|2.22|size= 0.75}}, an alt syntax is added, which allows to return parents identical to [[BIS_fnc_returnParents]] (see Example 2)
groups:
- Config
syntax:
- call: !Unary config
  ret:
    type: ArrayUnknown
    desc: array of parent [[Config]]s, ordered from parent to child
  params:
  - name: config
    desc: target config
    type: Config
argument_loc: Unspecified
effect_loc: Unspecified
since:
  arma3: '1.48'
examples:
- |-
  <sqf>
  _hierarchy = configHierarchy (configFile >> "CfgVehicles" >> "Car");
  // Returns [bin\config.bin, bin\config.bin/CfgVehicles, bin\config.bin/CfgVehicles/Car]
  </sqf>
- |-
  <sqf>
  _bis_fnc_returnParents = configHierarchy [configFile >> "CfgVehicles" >> "Land_FirePlace_F", true, true, true, true];
  // Returns ["Land_FirePlace_F","House_F","House","HouseBase","NonStrategic","Building","Static","All"]
  </sqf>
see_also:
- configClasses
- configProperties
- missionConfigFile
- campaignConfigFile
- a
- /
- b
- config
- greater
- greater
- name|config
- '>>'
- name
- configName
- count
- getArray
- getText
- getNumber
- inheritsFrom
- isArray
- isClass
- isNumber
- isText
- select
- isKindOf
- BIS_fnc_returnParents
