name: configHierarchy
desc: Returns hierarchy of the given config class. Just like with [[inheritsFrom]], only complete config classes are supported (before {{GVI|arma3|2.14|size= 0.75}}). Since {{GVI|arma3|2.22|size= 0.75}}, an alt syntax is added, which allows to return parents identical to [[BIS_fnc_returnParents]] (see Example 2)
groups:
- Config
syntax:
- call: !Unary config
  ret:
    type: !ArrayUnsized
      type: Config
      desc: ''
    desc: ordered from parent to child
  right: !Item
    name: config
    desc: target config
    type: Config
- call: !Unary
  - config
  - classesOnly
  - includeBases
  - reversedOrder
  - configNames
  ret:
    type: !OneOf
    - type: !ArrayUnsized
        type: Config
        desc: ''
      desc: null
      since: null
    - type: String
      desc: null
      since: null
    desc: Strings represent config names
  right: !Array
  - !Item
    name: config
    desc: target config
    type: Config
  - !Item
    name: classesOnly
    desc: when [[true]], only classes are included in output and not properties
    type: Boolean
  - !Item
    name: includeBases
    desc: when [[true]], returned parents will include base classes (see description)
    type: Boolean
  - !Item
    name: reversedOrder
    desc: when [[true]], the return order is from child to parent
    type: Boolean
  - !Item
    name: configNames
    desc: 'when [[true]], the return is [[Array]] of [[String]]s, when [[false]] - [[Array]] of [[Config]]s. Default: [[false]]'
    type: Unknown
  since:
    arma3: '2.22'
argument_loc: Unspecified
effect_loc: Unspecified
since:
  arma3: '1.48'
examples:
- |-
  <sqf>
  _hierarchy = configHierarchy (configFile >> "CfgVehicles" >> "Car");
  // Returns [bin\config.bin, bin\config.bin/CfgVehicles, bin\config.bin/CfgVehicles/Car]
  </sqf>
- |-
  <sqf>
  _bis_fnc_returnParents = configHierarchy [configFile >> "CfgVehicles" >> "Land_FirePlace_F", true, true, true, true];
  // Returns ["Land_FirePlace_F","House_F","House","HouseBase","NonStrategic","Building","Static","All"]
  </sqf>
see_also:
- configClasses
- configProperties
- missionConfigFile
- campaignConfigFile
- a
- /
- b
- config
- greater
- greater
- name|config
- '>>'
- name
- configName
- count
- getArray
- getText
- getNumber
- inheritsFrom
- isArray
- isClass
- isNumber
- isText
- select
- isKindOf
- BIS_fnc_returnParents
