name: configOf
desc: Returns config path of the provided object.
groups:
- Config
syntax:
- ret:
    type: Config
  right: !Item
    name: object
    type: Object
argument_loc: Global
effect_loc: Unspecified
since:
  arma3: '2.0'
examples:
- <sqf>configOf player; // returns bin\config.bin/CfgVehicles/B_W_Soldier_TL_F</sqf>
see_also:
- typeOf
