name: configProperties
desc: |-
  Returns an array of config entries that meet the criteria in the condition code. The command iterates through available classes and config properties for given config entry.
  Current looked at config is stored in _x variable (similar to alternative [[count]] command implementation).
  The condition has to return [[true]] in order for the looked at property to be added to the resulting array. This command is a bit slower than [[configClasses]] but allows to access inherited entries.
groups:
- Config
syntax:
- call: !Unary
  - config
  - condition
  - inherit
  ret:
    type: !ArrayUnsized
      type: Config
      desc: ''
  right: !Array
  - !Item
    name: config
    desc: config entry to search
    type: Config
  - !Item
    name: condition
    type: Unknown
    optional: true
  - !Item
    name: inherit
    desc: include inherited properties
    type: Boolean
    optional: true
    default: '[[true]]'
argument_loc: Unspecified
effect_loc: Unspecified
since:
  arma3: '1.36'
examples:
- <sqf>_configs = configProperties [configFile >> "CfgVehicles" >> "O_Truck_02_box_F"];</sqf>
- <sqf>_configs = configProperties [configFile >> "RscText", "true", true];</sqf>
- "Get all hitpoints of a truck:\n<sqf>\n_hitPoints = [];\n_hitPointsCfgs = configProperties [\n\tconfigFile >> \"CfgVehicles\" >> \"O_Truck_02_box_F\" >> \"HitPoints\", \n\t\"true\", \n\ttrue\n];\nhint str _hitPointsCfgs;\n</sqf>"
see_also:
- Config
- configFile
- missionConfigFile
- configClasses
- configHierarchy
