name: configHierarchy
description: Returns hierarchy of the given config class. Just like with [[inheritsFrom]], only complete config classes are supported (before {{GVI|arma3|2.14|size= 0.75}}). Since {{GVI|arma3|2.22|size= 0.75}}, an alt syntax is added, which allows to return parents identical to [[BIS_fnc_returnParents]] (see Example 2)
groups:
- Config
syntax:
- call: !Unary config
  ret:
  - Unknown
  - ordered from parent to child
  params:
  - name: config
    description: target config
    type: Config
- call: !Unary
  - config
  - classesOnly
  - includeBases
  - reversedOrder
  - configNames
  ret:
  - Unknown
  - Strings represent config names
  params:
  - name: config
    description: target config
    type: Config
  - name: classesOnly
    description: when [[true]], only classes are included in output and not properties
    type: Boolean
  - name: includeBases
    description: when [[true]], returned parents will include base classes (see description)
    type: Boolean
  - name: reversedOrder
    description: when [[true]], the return order is from child to parent
    type: Boolean
  - name: configNames
    description: 'when [[true]], the return is [[Array]] of [[String]]s, when [[false]] - [[Array]] of [[Config]]s. Default: [[false]]'
    type: Unknown
  since:
    arma_3:
      major: 2
      minor: 22
argument_loc: Unspecified
effect_loc: Unspecified
since:
  arma_3:
    major: 1
    minor: 48
examples:
- |-
  <sqf>
  _hierarchy = configHierarchy (configFile >> "CfgVehicles" >> "Car");
  // Returns [bin\config.bin, bin\config.bin/CfgVehicles, bin\config.bin/CfgVehicles/Car]
  </sqf>
- |-
  <sqf>
  _bis_fnc_returnParents = configHierarchy [configFile >> "CfgVehicles" >> "Land_FirePlace_F", true, true, true, true];
  // Returns ["Land_FirePlace_F","House_F","House","HouseBase","NonStrategic","Building","Static","All"]
  </sqf>
