name: configSourceMod
desc: Returns modDir of the mod that given config class was loaded from.
groups:
- Mods and Addons
syntax:
- call: !Unary config
  ret:
    type: String
  right: !Item
    name: config
    type: Config
argument_loc: Unspecified
effect_loc: Unspecified
since: {}
examples:
- <sqf>configSourceMod (configFile >> "CfgVehicles" >> "Heli_Transport_04_base_F"); // returns "heli"</sqf>
- <sqf>configSourceMod (configFile >> "CfgVehicles" >> "Car"); // returns "A3"</sqf>
see_also:
- configFile
- configSourceModList
- modParams
