name: diag_exportConfig
desc: Exports given [[Config|config]] into file of given path.
groups:
- Diagnostic
- Config
syntax:
- call: !Unary
  - path
  - config
  ret:
    type: Nothing
  params:
  - name: path
    desc: file path on disc
    type: String
  - name: config
    desc: the config you would like to export
    type: Config
argument_loc: Unspecified
effect_loc: Unspecified
since:
  arma3: '2.2'
examples:
- |-
  export an [[Arma: All-in-one Config|All-in-One config]]:
  <sqf>diag_exportConfig ["O:/config.cpp", configFile];</sqf>
see_also:
- configFile
