name: enableEnvironment
desc: |-
  Enable/disable environmental effects: ambient life and/or ambient sound.

  {{Feature|informative|This command has to be executed after mission start: be sure to use e.g <sqf inline>sleep 0.1;</sqf> for it to take effect.}}
  Influenced sounds among others are:
  {{Columns|2|
  * bird sounds
  * insect sounds
  * waves
  * wind
  * rain
  * sounds produced by air conditioners and similar
  }}
  * {{GVI|arma3|2.06|size= 0.75}} thunder (an already started sound will not be cut but future ones will be prevented)
groups:
- Environment
- Sounds
syntax:
- call: !Unary enable
  ret:
    type: Nothing
  right: !Item
    name: enable
    desc: '[[false]] to disable ambient life and ambient sounds, [[true]] to re-enable it'
    type: Boolean
- call: !Unary
  - ambientLife
  - ambientSound
  - windyCoef
  ret:
    type: Nothing
  right: !Array
  - !Item
    name: ambientLife
    desc: enable/disable ambient life (bees, rabbits, birds, snakes, fish)
    type: Boolean
  - !Item
    name: ambientSound
    desc: enable/disable ambient sounds (cicadas, owls, etc)
    type: Boolean
  - !Item
    name: windyCoef
    desc: howling wind at heights, range 0..1
    type: Number
    optional: true
    default: '1'
    since:
      arma3: '2.12'
  since:
    arma3: '1.68'
argument_loc: Unspecified
effect_loc: Local
since:
  arma1: '1.0'
  arma2: '1.0'
  arma2oa: '1.50'
  tkoh: '1.0'
  arma3: '0.50'
examples:
- <sqf>enableEnvironment false; // identical to enableEnvironment [false, false]</sqf>
- |-
  <sqf>
  enableEnvironment [false, true];
  enableEnvironment [false, true, 0.5]; // since {{arma3}} v2.12
  </sqf>
see_also:
- environmentEnabled
- fadeEnvironment
- environmentVolume
- initAmbientLife
- sideAmbientLife
- getAllEnvSoundControllers
- getEnvSoundController
- setSoundEffect
- Arma
- '3:'
- 'Animals:'
- Ambient
- System
