name: environmentVolume
desc: Returns the current environment volume (set by [[fadeEnvironment]])
groups:
- Sounds
syntax:
- call: Nular
  ret:
    type: Number
argument_loc: Unspecified
effect_loc: Unspecified
since: {}
examples:
- <sqf>hint str environmentVolume;</sqf>
see_also:
- fadeEnvironment
- musicVolume
- soundVolume
- radioVolume
- speechVolume
- getAudioOptionVolumes
- environmentEnabled
