name: environmentEnabled
desc: Returns status of [[enableEnvironment]] command
groups:
- Environment
- Sounds
syntax:
- call: Nular
  ret:
    type: Unknown
    desc: see [[enableEnvironment]]
argument_loc: Unspecified
effect_loc: Unspecified
since:
  arma3: '1.68'
examples:
- <sqf>private _enabled = environmentEnabled;</sqf>
see_also:
- enableEnvironment
- fadeEnvironment
- environmentVolume
- initAmbientLife
- sideAmbientLife
- getAllEnvSoundControllers
- getEnvSoundController
- setSoundEffect
