name: getArtilleryComputerSettings
desc: Returns settings from current vehicle weapon manned by player.
groups:
- Artillery
syntax:
- call: Nular
  ret:
    type: Unknown
argument_loc: Unspecified
effect_loc: Unspecified
since:
  arma3: '0.50'
examples:
- <sqf>hint str getArtilleryComputerSettings; // ["Semi (medium)", "HE Mortar Shells", 0]</sqf>
see_also:
- shownArtilleryComputer
- enableEngineArtillery
- commandArtilleryFire
- doArtilleryFire
- getArtilleryETA
- inRangeOfArtillery
- getArtilleryAmmo
