name: getGraphValues
desc: Generate graph y - coordinates of all input values within specific x and y range.
groups:
- Math
syntax:
- call: !Unary
  - - graphMinX
    - graphMaxX
    - graphMinY
    - graphMaxY
    - valueCount
    - randomOffset
  - x1
  - y1
  - x2
  - y2
  - '...'
  ret:
    type: Unknown
  params:
  - name: graphMinX
    desc: minimum x-axis value
    type: Number
  - name: graphMaxX
    desc: maximum x-axis value
    type: Number
  - name: graphMinY
    desc: minimum y-axis value
    type: Number
  - name: graphMaxY
    desc: maximum y-axis value
    type: Number
  - name: valueCount
    desc: number of values the returned array should have
    type: Number
  - name: randomOffset
    desc: random range for returned y value
    type: Number
  - name: xN
    desc: n<sup>th</sup> x value
    type: Number
  - name: yN
    desc: n<sup>th</sup> y value
    type: Number
argument_loc: Unspecified
effect_loc: Unspecified
since:
  arma3: '1.92'
examples:
- "<sqf>\nprivate _minX = 0;\nprivate _maxX = 10;\nprivate _minY = 0;\nprivate _maxY = 100;\nprivate _count = 11;\nprivate _random = 0;\n\ngetGraphValues [\n\t[_minX, _maxX, _minY, _maxY, _count, _random],\n\t0, 5,\n\t1, 10,\n\t2, 100,\n\t3, 50,\n\t4, 30,\n\t5, 100,\n\t6, 10,\n\t7, 50,\n\t8, 75,\n\t9, 100,\n\t10, 100\n];\n/*\n\treturns [[0.05, 0.1, 1, 0.5, 0.3, 1, 0.1, 0.5, 0.75, 1, 1], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]\n\tsupposedly [array of 1-based Y values, array of X values]\n*/\n</sqf>"
see_also:
- decayGraphValues
