name: serverConfigTopLevelEntry
desc: 'Get top-level entry (i.e. entry directly below config root) of the desired name from the {{Link|Arma 3: Server Config File|server config}}, making it some kind of secured ''''''''''serverConfigFile'''''''''' command.'
multiplayer_note: Only works on '''dedicated''' servers.
groups:
- Argo
syntax:
- call: !Unary configEntry
  ret:
    type: Config
    desc: requested server config entry or [[configNull]] on error
  right: !Item
    name: configEntry
    desc: 'any [[Arma 3: Server Config File|server config]] entry but {{hl|password}} and {{hl|passwordAdmin}} which are ignored'
    type: String
argument_loc: Unspecified
effect_loc: Unspecified
server_exec: true
since:
  argo: '1.0'
examples:
- <sqf>_kickDupes = getNumber serverConfigTopLevelEntry "kickDuplicate" != 0;</sqf>
see_also:
- Arma
- '3:'
- Server
- Config
- File
- configFile
- config
- greater
- greater
- name|config
- '>>'
- name
