name: values
desc: Returns all values stored in the given [[HashMap]]. The order of the returned Array corresponds to the order of the Array returned by the [[keys]] command.
groups:
- HashMap
syntax:
- ret:
    type: ArrayUnknown
    desc: all values stored in ''hashmap''
  right: !Item
    name: hashmap
    type: HashMapUnknown
argument_loc: Unspecified
effect_loc: Unspecified
since:
  arma3: '2.4'
examples:
- <sqf>private _values = values _myHashMap;</sqf>
see_also:
- keys
- toArray
